### ISSUE TITLE
Couldn't install on Blender 2.93 - see attached screen shot for list of errors

### ISSUE THREAD

**Issue by StoneHexagon** [PavelBlend/Blender-Molecular-Script#2]
![Errors](https://user-images.githubusercontent.com/55412779/131401898-33a8c43d-d8fe-4c0a-a41e-10577ddcadcc.png)

**Comment by StoneHexagon** [comment]
Windows 10 with latest updates installed. Chrome, Word, Soundcloud, Adobe Acrobat, Photoshop, Sublime all open at time error occurred.

**Comment by MutableLoss** [comment]
Yep, time.clock was removed in 3.8, and had a depreciation warning in 3.7. Since Blender 2.93 introduced Python 3.9 this would explain the cause of the error.

https://bugs.python.org/issue31803

Looks like time.process_time() is the acceptable replacement:
https://stackoverflow.com/questions/85451/pythons-time-clock-vs-time-time-accuracy
