### ISSUE TITLE
Colaboration on Molecular / Plus 

### ISSUE THREAD

**Issue by u3dreal** [PavelBlend/Blender-Molecular-Script#3]
Hi Plavel .. without knowing you were carrying on  .. i was developing molecular plus on my branch ..

https://github.com/u3dreal/molecular-plus

I mainly added gui and textures for the broken channel ...
I saw a post on taichi forum were you were asking about rewriting molecular using taichi ..
I had the exact same idea ... how is your plan grow ?

I would like to colaborate !!  Let me know . u3dreal

**Comment by PavelBlend** [comment]
@u3dreal Hi.

I don't want to use taichi anymore. I want to ditch python and its libraries entirely. I think molecular is better rewritten in c (not c ++, cython). But at the moment I don't know the c language well. It is also necessary not to use the standard blender particle system. Because it takes a long time to import and export data from molecular core and blender. All calculations need to be done in the molecular core. Blender must export data in the molecular core once at the start of the simulation. The code for collision objects will need to be written in the kernel. Perhaps it will be possible to adapt the code from the blender source code.

But I have no experience for this task. Because of this, I am not designing molecular. I don't want to modify the existing molecular version, as it works slowly and depends on the standard blender functions because of what the addon does unnecessary work.

I want to be able to create simulations with 10 million particles in a reasonable amount of time (10-20 hours).
This is not possible now. And if you succeed in creating such a simulation, then the miscalculation will take a week.

**Comment by u3dreal** [comment]
OK makes sense.

**Comment by OmidGhotbi** [comment]
can i ask why you ditched Taichi, last time i checked it's worked with C as AOT i tried it and it was quiet good too, because you have more experience with it can i ask you for your professional advice?
