### ISSUE TITLE
different results from Cython version with same settings

### ISSUE THREAD

**Issue by OmidGhotbi** [PavelBlend/Blender-Molecular-Script#5]
i will get completely different results from Cython version with same settings.

**Comment by OmidGhotbi** [comment]
i believe i found the issue. it's because of the particle size that needs to be set manually, if particles intersect or gap they will act unexpectedly and the behavior of particles can not be protected or it will cause instability.
i modified the add-on to set the size of particles in the viewport and render according to grid resolution and it's getting much closer and I see less crash as well.

**Comment by PavelBlend** [comment]
I removed the Tension setting. Perhaps the result is different because of this?

**Comment by OmidGhotbi** [comment]
is there a reason behind removing the Tension? can I add it back?

**Comment by PavelBlend** [comment]
I wanted to get rid of unnecessary settings. So that the addon is easier to configure and does not have a large number of settings. I haven't found any use for the tension parameter. This parameter increases the communication length. I don't know why this is needed. If you want, restore this setting.

**Comment by OmidGhotbi** [comment]
ok thank you

**Comment by OmidGhotbi** [comment]
Fixed.
