### ISSUE TITLE
used less than 12% of cpu as Cython

### ISSUE THREAD

**Issue by OmidGhotbi** [PavelBlend/Blender-Molecular-Script#8]
used less than 12% of CPU as Cython

**Comment by PavelBlend** [comment]
I don't currently have much experience programming in C. So I can't say for sure why the addon uses so little CPU capacity. The molecular core is practically the first program I wrote in C. Therefore, this problem will not be solved quickly. My idea is to rewrite the addon in the future so that it does not depend on blender's particle and collision system. This will allow you to export particles once, at the beginning of the simulation, and then perform all calculations in the C core, without importing/exporting data from/to Python. Perhaps this will solve the problem of low performance.

**Comment by OmidGhotbi** [comment]
great idea. because it may be the issue with GIL lock in python. so naturally if you offload all the simulation one c it will bypass the GIL lock as well.
